spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: Trouve Ton Match
  datasource:
    url: jdbc:postgresql://localhost:5432/ttm
    username: postgres
    password: postgres
  thymeleaf:
    enable-spring-el-compiler: true
  jpa:
      database: postgresql
      show-sql: true
      hibernate:
        ddl-auto: create-drop
  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /docs

server:
  port: 8080