spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: Trouve Ton Match
  datasource:
    url: jdbc:postgresql://localhost:5432/ttmv2
    username: postgres
    password: postgres
  thymeleaf:
    enable-spring-el-compiler: true
  jpa:
    database: postgresql
    show-sql: true
    hibernate:
      ddl-auto: none
  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/changelog.xml

  springdoc:
    api-docs:
      path: /api-docs
    swagger-ui:
      path: /docs

app:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  jwt-expiration-milliseconds: 604800000 #représente 7 jours

#debug:
#  true
server:
  port: 8080

logging:
  level:
    org:
      springframework:
        DEBUG